# Generated by Django 3.0.6 on 2020-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_fd_mf_sebi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indian_Indices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Currrent_value', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
                ('Per_change', models.FloatField(default=0)),
                ('Open', models.FloatField(default=0)),
                ('High', models.FloatField(default=0)),
                ('Low', models.FloatField(default=0)),
            ],
        ),
    ]
