# Generated by Django 3.0.6 on 2020-05-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_chart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chart',
            new_name='graph',
        ),
    ]
